# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_id', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('logo', models.CharField(max_length=800)),
                ('address', models.CharField(max_length=800)),
                ('phone_number', models.CharField(max_length=800)),
                ('url', models.CharField(max_length=800)),
            ],
        ),
    ]
